# Generated by Django 2.2.7 on 2020-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentClick',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='totalClick',
            field=models.IntegerField(default=0),
        ),
    ]
